apiVersion: v1
kind: DataConnection
metadata:
  name: aws-connection-pipeline-s3
  namespace: jh-project
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/managed: "true"
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: "Pipeline S3 (jh-project)"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: FROM_CREDENTIALS_SCRIPT
  AWS_SECRET_ACCESS_KEY: FROM_CREDENTIALS_SCRIPT
  AWS_S3_BUCKET: pipeline-artifacts
  AWS_S3_ENDPOINT: http://rustfs-s3.jh-project-shared.svc.cluster.local:9000
  AWS_DEFAULT_REGION: us-east-1
---
apiVersion: v1
kind: DataConnection
metadata:
  name: aws-connection-pipeline-s3
  namespace: jh-project-shared
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/managed: "true"
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: "Pipeline S3 (jh-project)"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: FROM_CREDENTIALS_SCRIPT
  AWS_SECRET_ACCESS_KEY: FROM_CREDENTIALS_SCRIPT
  AWS_S3_BUCKET: pipeline-artifacts
  AWS_S3_ENDPOINT: http://rustfs-s3.jh-project-shared.svc.cluster.local:9000
  AWS_DEFAULT_REGION: us-east-1
