apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhoai
  namespace: openshift-gitops-rhoai
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/CCI-MOC/ai-accelerator.git
    targetRevision: main
    path: components/operators/openshift-ai/aggregate/overlays/stable-3.x-nvidia-gpu
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops-rhoai
