apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: jh-project-rustfs
  namespace: jh-project
  labels:
    tenant: jh-project
    app: rustfs
spec:
  podMetricsEndpoints:
    - port: api
      path: /health
      interval: 30s
      relabelings:
        - sourceLabels:
            - __meta_kubernetes_pod_label_app
          targetLabel: workload
  selector:
    matchLabels:
      app: rustfs
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: jh-project-workbench
  namespace: jh-project
  labels:
    tenant: jh-project
    app: jhwrkbch1
spec:
  podMetricsEndpoints:
    - port: notebook-port
      path: /notebook/jh-project/jhwrkbch1/api
      interval: 30s
      relabelings:
        - sourceLabels:
            - __meta_kubernetes_pod_label_app
          targetLabel: workload
    - port: kube-rbac-proxy
      path: /healthz
      interval: 30s
      scheme: HTTPS
      tlsConfig:
        insecureSkipVerify: true
      relabelings:
        - sourceLabels:
            - __meta_kubernetes_pod_label_app
          targetLabel: workload
  selector:
    matchLabels:
      app: jhwrkbch1
