apiVersion: v1
kind: ResourceQuota
metadata:
  name: customer-quota-shared
  namespace: cust-project-shared
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  hard:
    limits.cpu: '16'
    limits.memory: 32Gi
    limits.nvidia.com/gpu: '0'
    pods: '30'
    requests.cpu: '8'
    requests.memory: 16Gi
    requests.nvidia.com/gpu: '0'
