apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pipelines-definition
  namespace: jh-project-shared
  labels:
    app: mariadb-pipelines-definition
    component: data-science-pipelines
    dspa: pipelines-definition
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
