apiVersion: v1
kind: Secret
metadata:
  name: mariadb-pipelines-definition
  namespace: jh-project-shared
  labels:
    app: mariadb-pipelines-definition
    component: data-science-pipelines
    dspa: pipelines-definition
type: Opaque
stringData:
  mysql_root_password: mysql123!
  mysql_username: mlpipeline
  mysql_password: mysql123!
