apiVersion: v1
kind: Service
metadata:
  name: rustfs-s3
  namespace: jh-project-shared
  labels:
    app: rustfs
spec:
  ports:
    - port: 9000
      targetPort: 9000
      name: api
  selector:
    app: rustfs
---
apiVersion: v1
kind: Service
metadata:
  name: rustfs-console
  namespace: jh-project-shared
  labels:
    app: rustfs
spec:
  ports:
    - port: 9001
      targetPort: 9001
      name: console
  selector:
    app: rustfs
