apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: pipelines-definition
  namespace: jh-project
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  apiServer:
    enableSamplePipeline: false
    enableOauth: true
    deploy: true
  database:
    mariaDB:
      deploy: true
      pipelineDBName: mlpipeline
      pvcSize: 10Gi
      username: mlpipeline
  dspVersion: v2
  objectStorage:
    externalStorage:
      bucket: pipeline-artifacts
      host: rustfs-s3.jh-project-shared.svc.cluster.local:9000
      port: "9000"
      region: us-east-1
      scheme: http
      s3CredentialsSecret:
        accessKey: AWS_ACCESS_KEY_ID
        secretKey: AWS_SECRET_ACCESS_KEY
        secretName: aws-connection-pipeline-s3
  persistenceAgent:
    deploy: true
  scheduledWorkflow:
    deploy: true
