apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhoai-app-of-apps
  namespace: openshift-gitops-rhoai
spec:
  project: default
  source:
    repoURL: https://github.com/CCI-MOC/ai-accelerator.git
    targetRevision: main
    path: openshift-gitops/applications
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops-rhoai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
