apiVersion: v1
kind: ResourceQuota
metadata:
  name: customer-quota-gpu
  namespace: cust-project
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  hard:
    requests.cpu: "8"
    limits.cpu: "16"
    requests.memory: "16Gi"
    limits.memory: "64Gi"
    requests.nvidia.com/gpu: "1"
    limits.nvidia.com/gpu: "1"
    pods: "20"
