apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- rb-jh-project-admins-binding.yaml
- rb-jh-project-cpu-users-binding.yaml
- rb-jh-project-gpu-users-binding.yaml
- rb-jh-project-viewers-binding.yaml
