apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-tenants
spec:
  generators:
  - list:
      elements:
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: customer-project
          path: customers/customer-project
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: customer-project-shared
          path: customers/customer-project-shared
