apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- group-cust-project-admins.yaml
- group-cust-project-gpu-users.yaml
- group-cust-project-viewers.yaml
- group-cust-project-cpu-users.yaml
- rb-cust-project-admins-binding.yaml
- rb-cust-project-cpu-users-binding.yaml
- rb-cust-project-gpu-users-binding.yaml
- rb-cust-project-viewers-binding.yaml
