apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: admin-workbench-pvc
  namespace: jh-project
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3-csi
  volumeMode: Filesystem
  volumeName: pvc-b81b2038-52b3-41c1-96ae-3dd3780b1b02
