apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-workbench-kube-rbac-proxy-config
  namespace: jh-project
data:
  config-file.yaml: |
    authorization:
      resourceAttributes:
        apiVersion: kubeflow.org/v1
        apiGroup: kubeflow.org
        resource: notebooks
        subresource: admin-workbench
        namespace: jh-project
        verb: get
