apiVersion: batch/v1
kind: Job
metadata:
  name: jhwrkbch1-tls-init
  namespace: jh-project
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
        - name: tls-init
          image: registry.redhat.io/rhel9/support-tools:latest
          command:
            - /bin/sh
            - -c
            - |
              openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
                -keyout /tmp/tls.key -out /tmp/tls.crt \
                -subj "/CN=jhwrkbch1-jh-project" -addext "subjectAltName=DNS:jhwrkbch1-jh-project,DNS:*.jh-project.svc"
              kubectl create secret tls jhwrkbch1-kube-rbac-proxy-tls \
                --cert=/tmp/tls.crt --key=/tmp/tls.key \
                --namespace jh-project --dry-run=client -o yaml | kubectl apply -f -
      restartPolicy: Never
      serviceAccountName: jhwrkbch1-tls-init
