apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- sa-admin.yaml
- sa-admin-workbench.yaml
- rb-admin-workbench-tls-init.yaml
- admin-workbench-tls-init.yaml
- wb-admin.yaml
- admin-workbench-pvc-pvc.yaml
- admin-workbench-kube-rbac-proxy-config.yaml
- admin-workbench.yaml
