apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin-workbench-tls-init
  namespace: jh-project
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get"]
  resourceNames: ["admin-workbench-kube-rbac-proxy-tls"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-workbench-tls-init
  namespace: jh-project
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin-workbench-tls-init
subjects:
- kind: ServiceAccount
  name: admin-workbench
  namespace: jh-project
