apiVersion: v1
kind: ServiceAccount
metadata:
  name: jhwrkbch1-tls-init
  namespace: jh-project
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jhwrkbch1-tls-init
  namespace: jh-project
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jhwrkbch1-tls-init
  namespace: jh-project
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jhwrkbch1-tls-init
subjects:
  - kind: ServiceAccount
    name: jhwrkbch1-tls-init
    namespace: jh-project
