apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustfs-data-block
  namespace: jh-project
spec:
  storageClassName: px-csi-replicated
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
